spring:
  datasource:
    url: jdbc:h2:mem:testdb     # H2 Database URL
    driver-class-name: org.h2.Driver  # H2 driver class
    username: sa                # Default H2 username
    password:                   # Default H2 password (empty by default)
  h2:
    console:
      enabled: true             # Enable H2 console
      path: /h2-console         # URL path to access H2 console
  jpa:
    hibernate:
      ddl-auto: create         # Database schema update strategy
    show-sql: true              # Show SQL queries in logs
